spring:
  #通用数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.173.199:3307/mall-order?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sample.mall.order.model

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000